//! The HTTP control API (docs/30 "Cloud HTTP control API").

use std::sync::Arc;

use axum::body::Bytes;
use axum::extract::{Path, Query, State};
use axum::http::{HeaderMap, HeaderValue, StatusCode, header};
use axum::middleware::{self, Next};
use axum::response::{IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use modbit_domain::approval::ApprovalEvent;
use modbit_domain::event::AggregateType;
use modbit_domain::session::SessionEvent;
use modbit_domain::task::{InputMode, TaskEvent, TaskOrigin, TaskState};
use modbit_domain::{ApprovalId, SessionId, SpaceId, TaskId, TenantId, UserId, WorkspaceId};
use modbit_event_store::AppendRequest;
use modbit_event_store::cloud::{CloudError, Principal, api_actor, new_event};
use serde_json::{Value, json};

use crate::AppState;

/// The API's error envelope: a stable code, a message and the request id.
#[derive(Debug)]
pub struct ApiError {
    /// HTTP status.
    pub status: StatusCode,
    /// Stable code.
    pub code: &'static str,
    /// Message.
    pub message: String,
}

impl ApiError {
    pub(crate) fn new(status: StatusCode, code: &'static str, message: impl Into<String>) -> Self {
        Self {
            status,
            code,
            message: message.into(),
        }
    }
    pub(crate) fn bad(message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, "BAD_PAYLOAD", message)
    }
    pub(crate) fn not_found(what: impl Into<String>) -> Self {
        Self::new(StatusCode::NOT_FOUND, "NOT_FOUND", what)
    }
}

impl From<CloudError> for ApiError {
    fn from(e: CloudError) -> Self {
        match e {
            CloudError::NotFound(w) => Self::not_found(w),
            CloudError::SequenceConflict { .. } => {
                Self::new(StatusCode::CONFLICT, "SEQUENCE_CONFLICT", e.to_string())
            }
            CloudError::InvalidTransition(w) => {
                Self::new(StatusCode::CONFLICT, "INVALID_TRANSITION", w)
            }
            CloudError::Json(e) => Self::bad(e.to_string()),
            other => Self::new(
                StatusCode::INTERNAL_SERVER_ERROR,
                "STORE",
                other.to_string(),
            ),
        }
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        (
            self.status,
            Json(json!({"code": self.code, "message": self.message})),
        )
            .into_response()
    }
}

pub(crate) type ApiResult<T> = Result<T, ApiError>;

/// The authenticated caller, attached to the request by the middleware.
#[derive(Clone, Debug)]
pub struct Caller(pub Principal);

fn request_id(headers: &HeaderMap) -> String {
    headers
        .get("x-request-id")
        .and_then(|v| v.to_str().ok())
        .map(str::to_owned)
        .unwrap_or_default()
}

/// Every response carries the request id (set or generated by the layer).
async fn stamp_request_id(req: axum::extract::Request, next: Next) -> Response {
    let id = req
        .headers()
        .get("x-request-id")
        .and_then(|v| v.to_str().ok())
        .filter(|v| !v.is_empty() && v.len() <= 128)
        .map(str::to_owned)
        .unwrap_or_else(|| uuid::Uuid::now_v7().to_string());
    let mut req = req;
    req.headers_mut().insert(
        "x-request-id",
        HeaderValue::from_str(&id).unwrap_or(HeaderValue::from_static("")),
    );
    let mut res = next.run(req).await;
    res.headers_mut().insert(
        "x-request-id",
        HeaderValue::from_str(&id).unwrap_or(HeaderValue::from_static("")),
    );
    res
}

/// Bearer authentication and the per-principal rate limit, before any handler.
async fn authenticate(
    State(state): State<Arc<AppState>>,
    mut req: axum::extract::Request,
    next: Next,
) -> Response {
    let token = req
        .headers()
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("Bearer "))
        .map(str::trim)
        .unwrap_or_default()
        .to_owned();
    let Some(claims) = state.key.verify(&token) else {
        return ApiError::new(
            StatusCode::UNAUTHORIZED,
            "UNAUTHENTICATED",
            "a valid bearer access token is required",
        )
        .into_response();
    };
    let Some(principal) = claims.principal() else {
        return ApiError::new(
            StatusCode::UNAUTHORIZED,
            "UNAUTHENTICATED",
            "malformed claims",
        )
        .into_response();
    };
    if !state.limiter.admit(&principal.principal_id.to_string()) {
        return ApiError::new(
            StatusCode::TOO_MANY_REQUESTS,
            "RATE_LIMITED",
            "too many requests for this principal; retry shortly",
        )
        .into_response();
    }
    req.extensions_mut().insert(Caller(principal));
    next.run(req).await
}

/// The router.
pub fn router(state: Arc<AppState>) -> Router {
    let authed = Router::new()
        .route("/v1/sessions", post(create_session))
        .route("/v1/sessions/{session_id}", get(get_session))
        .route("/v1/sessions/{session_id}/tasks", post(create_task))
        .route("/v1/tasks/{task_action}", post(task_action))
        .route("/v1/approvals/{approval_action}", post(approval_action))
        .route("/v1/events", get(events))
        .route("/v1/commands/{command_id}", get(get_command))
        .route("/v1/outputs/{hash}", get(output))
        .route("/v1/artifacts/{hash}", get(artifact))
        .route("/v1/objects", axum::routing::put(put_object))
        .route("/v1/handoffs", post(handoff))
        // PX-011: which repositories this tenant takes webhook deliveries for.
        .route(
            "/v1/forge/repositories",
            post(crate::forge::map_repository).get(crate::forge::list_repositories),
        )
        .route("/v1/stream", get(crate::stream::stream))
        // M8.8: the person's view of a cloud browser, through the worker's link.
        .route(
            "/v1/browser-sessions/{browser_session_id}/stream",
            get(crate::browser_view::browser_stream),
        )
        .route(
            "/v1/browser-sessions/{browser_action}",
            post(browser_action),
        )
        .route_layer(middleware::from_fn_with_state(
            Arc::clone(&state),
            authenticate,
        ));
    Router::new()
        .route("/v1/health", get(health))
        .route("/v1/auth/token", post(auth_token))
        .route("/v1/auth/refresh", post(auth_refresh))
        // M8.8: a worker's outbound link (worker bearer token, not a principal's).
        .route("/v1/workers/link", get(crate::browser_view::worker_link))
        // PX-011: the GitHub App's deliveries (signed under the app's secret, not a bearer).
        .route(
            "/v1/forge/github/webhook",
            post(crate::forge::github_webhook),
        )
        .merge(authed)
        .layer(middleware::from_fn(stamp_request_id))
        .layer(tower_http::limit::RequestBodyLimitLayer::new(
            64 * 1024 * 1024,
        ))
        .with_state(state)
}

/// `POST /v1/browser-sessions/{id}:input` | `:control` (M8.8).
async fn browser_action(
    state: State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(browser_action): Path<String>,
    body: Json<Value>,
) -> ApiResult<(StatusCode, Json<Value>)> {
    let (id, action) = browser_action
        .split_once(':')
        .ok_or_else(|| ApiError::bad("expected /v1/browser-sessions/{id}:input|:control"))?;
    let id = id.to_owned();
    match action {
        "input" => crate::browser_view::browser_input(state, ext, Path(id), body).await,
        "control" => crate::browser_view::browser_control(state, ext, Path(id), body).await,
        other => Err(ApiError::bad(format!("unknown browser action `{other}`"))),
    }
}

async fn health() -> Json<Value> {
    Json(
        json!({"ok": true, "service": env!("CARGO_PKG_NAME"), "version": env!("CARGO_PKG_VERSION")}),
    )
}

fn token_response(state: &AppState, p: &Principal, refresh: String) -> Value {
    json!({
        "access_token": state.key.issue(p, state.access_ttl_ms),
        "expires_in_ms": state.access_ttl_ms,
        "refresh_token": refresh,
        "principal_id": p.principal_id.to_string(),
        "tenant_id": p.tenant_id.to_string(),
        "kind": p.kind,
        "label": p.label,
    })
}

/// `POST /v1/auth/token {secret}`: a principal's secret for a token pair.
async fn auth_token(
    State(state): State<Arc<AppState>>,
    Json(body): Json<Value>,
) -> ApiResult<Json<Value>> {
    let secret = body["secret"].as_str().unwrap_or_default();
    if secret.is_empty() || secret.len() > 256 {
        return Err(ApiError::bad("secret required"));
    }
    if !state
        .limiter
        .admit(&format!("auth:{}", &secret[..secret.len().min(12)]))
    {
        return Err(ApiError::new(
            StatusCode::TOO_MANY_REQUESTS,
            "RATE_LIMITED",
            "too many attempts",
        ));
    }
    let Some(p) = state.store.principal_by_secret(secret).await? else {
        return Err(ApiError::new(
            StatusCode::UNAUTHORIZED,
            "UNAUTHENTICATED",
            "unknown or revoked secret",
        ));
    };
    let refresh = state
        .store
        .issue_refresh_token(&p, state.refresh_ttl_ms)
        .await?;
    Ok(Json(token_response(&state, &p, refresh)))
}

/// `POST /v1/auth/refresh {refresh_token}`: rotate; a replayed token revokes the family.
async fn auth_refresh(
    State(state): State<Arc<AppState>>,
    Json(body): Json<Value>,
) -> ApiResult<Json<Value>> {
    let token = body["refresh_token"].as_str().unwrap_or_default();
    if token.is_empty() {
        return Err(ApiError::bad("refresh_token required"));
    }
    let Some((p, fresh)) = state
        .store
        .rotate_refresh_token(token, state.refresh_ttl_ms)
        .await?
    else {
        return Err(ApiError::new(
            StatusCode::UNAUTHORIZED,
            "UNAUTHENTICATED",
            "refresh token unknown, expired, spent or revoked",
        ));
    };
    Ok(Json(token_response(&state, &p, fresh)))
}

fn command_id(body: &Value) -> ApiResult<uuid::Uuid> {
    body["command_id"]
        .as_str()
        .and_then(|s| uuid::Uuid::parse_str(s).ok())
        .ok_or_else(|| ApiError::bad("command_id (uuid) required"))
}

/// A retried command answers with what was recorded (docs/33 "Idempotency").
async fn replay(state: &AppState, tenant: TenantId, id: uuid::Uuid) -> ApiResult<Option<Response>> {
    let Some(rec) = state.store.command(tenant, id).await? else {
        return Ok(None);
    };
    let status = match rec.status.as_str() {
        "ACCEPTED" => StatusCode::OK,
        "PENDING" => StatusCode::ACCEPTED,
        _ => StatusCode::from_u16(rec.result["status"].as_u64().unwrap_or(409) as u16)
            .unwrap_or(StatusCode::CONFLICT),
    };
    let mut res = (status, Json(rec.result)).into_response();
    res.headers_mut()
        .insert("x-modbit-replayed", HeaderValue::from_static("true"));
    Ok(Some(res))
}

pub(crate) fn caller(req_ext: &axum::Extension<Caller>) -> Principal {
    req_ext.0.0.clone()
}

/// M8.2: while a worker holds the session's lease it is the only writer of
/// the session's log; a command that must run there is relayed —
/// recorded `PENDING` for the worker — and answered `202` with its id.
pub(crate) async fn relay_if_held(
    state: &AppState,
    p: &Principal,
    session: SessionId,
    cid: uuid::Uuid,
    kind: &str,
    body: Value,
) -> ApiResult<Option<Response>> {
    let Some((worker, generation)) = state.store.held_by(p.tenant_id, session).await? else {
        return Ok(None);
    };
    state
        .store
        .enqueue_command(p.tenant_id, session, cid, kind, body)
        .await?;
    Ok(Some(
        (
            StatusCode::ACCEPTED,
            Json(json!({"status": "PENDING", "command_id": cid.to_string(), "relayed_to": {"worker_id": worker, "generation": generation}})),
        )
            .into_response(),
    ))
}

/// `GET /v1/commands/{id}`: a command's recorded outcome (a relayed one until the owner completes it).
async fn get_command(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(command_id): Path<String>,
) -> ApiResult<Json<Value>> {
    let p = caller(&ext);
    let cid = parse_id(&command_id, |s| uuid::Uuid::parse_str(s).ok(), "command_id")?;
    let Some(rec) = state.store.command(p.tenant_id, cid).await? else {
        return Err(ApiError::not_found(format!("command {cid}")));
    };
    Ok(Json(
        json!({"command_id": rec.command_id.to_string(), "kind": rec.kind, "status": rec.status, "code": rec.code, "result": rec.result}),
    ))
}

/// `POST /v1/sessions {command_id}`.
async fn create_session(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Json(body): Json<Value>,
) -> ApiResult<Response> {
    let p = caller(&ext);
    let cid = command_id(&body)?;
    if let Some(r) = replay(&state, p.tenant_id, cid).await? {
        return Ok(r);
    }
    let session_id = SessionId::new();
    let user_id = if p.kind == "user" {
        UserId::from_bytes(*p.principal_id.as_bytes())
    } else {
        UserId::new()
    };
    let ev = new_event(
        "SessionCreated",
        &SessionEvent::SessionCreated {
            tenant_id: p.tenant_id,
            user_id,
            space_id: SpaceId::new(),
        },
        api_actor(&p),
    )?;
    let result = json!({"session_id": session_id.to_string()});
    let appended = state
        .store
        .append(
            AppendRequest {
                tenant_id: p.tenant_id,
                session_id,
                task_id: None,
                run_id: None,
                turn_id: None,
                step_id: None,
                aggregate_type: AggregateType::Session,
                aggregate_id: *session_id.as_bytes(),
                expected_sequence: Some(0),
                events: vec![ev],
            },
            Some((cid, "CreateSession", result.clone())),
        )
        .await?;
    let mut out = result;
    out["session_offset"] = json!(appended.session_offset);
    Ok((StatusCode::CREATED, Json(out)).into_response())
}

pub(crate) fn parse_id<T>(s: &str, parse: impl Fn(&str) -> Option<T>, what: &str) -> ApiResult<T> {
    parse(s).ok_or_else(|| ApiError::bad(format!("{what} must be a uuid")))
}

/// `GET /v1/sessions/{id}`: the projection.
async fn get_session(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(session_id): Path<String>,
) -> ApiResult<Json<Value>> {
    let p = caller(&ext);
    let sid = parse_id(&session_id, |s| SessionId::parse(s).ok(), "session_id")?;
    let Some((session, last)) = state.store.session(p.tenant_id, sid).await? else {
        state
            .store
            .record_denial(
                Some(p.tenant_id),
                Some(p.principal_id),
                &format!("session:{sid}"),
                "not in tenant",
            )
            .await?;
        return Err(ApiError::not_found(format!("session {sid}")));
    };
    let tasks = state.store.tasks_of(p.tenant_id, sid).await?;
    let lease = state.store.lease(p.tenant_id, sid).await?;
    Ok(Json(json!({
        "session": session,
        "last_session_offset": last,
        "tasks": tasks,
        "lease": lease.map(|(worker, generation, expires_at_ms, ready)| json!({"worker_id": worker, "generation": generation, "expires_at_ms": expires_at_ms, "ready": ready})),
    })))
}

/// `POST /v1/sessions/{id}/tasks {command_id, goal_text, workspace_root?, execution_profile?}`.
async fn create_task(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(session_id): Path<String>,
    Json(body): Json<Value>,
) -> ApiResult<Response> {
    let p = caller(&ext);
    let cid = command_id(&body)?;
    if let Some(r) = replay(&state, p.tenant_id, cid).await? {
        return Ok(r);
    }
    let sid = parse_id(&session_id, |s| SessionId::parse(s).ok(), "session_id")?;
    let goal = body["goal_text"]
        .as_str()
        .unwrap_or_default()
        .trim()
        .to_owned();
    if goal.is_empty() || goal.len() > 16 * 1024 {
        return Err(ApiError::bad("goal_text required (at most 16 KiB)"));
    }
    if state.store.session(p.tenant_id, sid).await?.is_none() {
        state
            .store
            .record_denial(
                Some(p.tenant_id),
                Some(p.principal_id),
                &format!("session:{sid}"),
                "not in tenant",
            )
            .await?;
        return Err(ApiError::not_found(format!("session {sid}")));
    }
    let profile = body["execution_profile"]
        .as_str()
        .unwrap_or("cloud_isolated")
        .to_owned();
    // IMP-EV-0072: what the task requires of the worker that will host it
    // (`capabilities`, e.g. `browser.control`), negotiated before dispatch:
    // a requirement no live worker serves is an explicit rejection on the
    // ledger; a served one is recorded on the session so only a worker
    // serving it claims the session.
    let requirements: Vec<String> = body["capabilities"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|c| c.as_str().map(str::to_owned))
                .collect()
        })
        .unwrap_or_default();
    if !requirements.is_empty() {
        let served = served_capabilities(&state).await?;
        let missing: Vec<&String> = requirements
            .iter()
            .filter(|c| !served.iter().any(|s| s == *c))
            .collect();
        if !missing.is_empty() {
            let result = json!({"code": "NO_CAPABLE_WORKER", "missing": missing, "served": served});
            state
                .store
                .record_rejection(p.tenant_id, cid, "CreateTask", "NO_CAPABLE_WORKER", result)
                .await?;
            return Err(ApiError::new(
                StatusCode::CONFLICT,
                "NO_CAPABLE_WORKER",
                format!("the task needs {missing:?}, which no live worker serves"),
            ));
        }
        state
            .store
            .require_for_session(p.tenant_id, sid, &requirements)
            .await?;
    }
    if let Some(r) = relay_if_held(
        &state,
        &p,
        sid,
        cid,
        "CreateTask",
        json!({"goal_text": goal, "execution_profile": profile, "workspace_root": body["workspace_root"], "base_revision": body["base_revision"]}),
    )
    .await?
    {
        return Ok(r);
    }
    // The task's id is its creating command's id — the same rule the Core
    // applies to `CreateTask`, so a task created here and one a worker
    // creates from a relayed command are named alike.
    let task_id = TaskId::from_bytes(*cid.as_bytes());
    let created = new_event(
        "TaskCreated",
        &TaskEvent::TaskCreated {
            session_id: sid,
            goal_text: goal.clone(),
            workspace_id: WorkspaceId::new(),
            workspace_root: body["workspace_root"].as_str().map(str::to_owned),
            base_revision: body["base_revision"].as_str().map(str::to_owned),
            execution_profile: profile.clone(),
            policy_profile_id: None,
            origin: TaskOrigin::Desktop,
        },
        api_actor(&p),
    )?;
    let queued = new_event("TaskQueued", &TaskEvent::TaskQueued, api_actor(&p))?;
    let result = json!({"task_id": task_id.to_string(), "session_id": sid.to_string(), "state": "QUEUED", "execution_profile": profile});
    state
        .store
        .append(
            AppendRequest {
                tenant_id: p.tenant_id,
                session_id: sid,
                task_id: Some(task_id),
                run_id: None,
                turn_id: None,
                step_id: None,
                aggregate_type: AggregateType::Task,
                aggregate_id: *task_id.as_bytes(),
                expected_sequence: Some(0),
                events: vec![created, queued],
            },
            Some((cid, "CreateTask", result.clone())),
        )
        .await?;
    state.store.mark_ready(p.tenant_id, sid).await?;
    Ok((StatusCode::CREATED, Json(result)).into_response())
}

/// `POST /v1/tasks/{task_id}:steer|:pause|:resume|:cancel`.
async fn task_action(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(seg): Path<String>,
    Json(body): Json<Value>,
) -> ApiResult<Response> {
    let p = caller(&ext);
    let (id, action) = seg.split_once(':').ok_or_else(|| {
        ApiError::bad("expected /v1/tasks/{task_id}:steer|:pause|:resume|:cancel")
    })?;
    let tid = parse_id(id, |s| TaskId::parse(s).ok(), "task_id")?;
    let cid = command_id(&body)?;
    if let Some(r) = replay(&state, p.tenant_id, cid).await? {
        return Ok(r);
    }
    let Some(task) = state.store.task(p.tenant_id, tid).await? else {
        state
            .store
            .record_denial(
                Some(p.tenant_id),
                Some(p.principal_id),
                &format!("task:{tid}"),
                "not in tenant",
            )
            .await?;
        return Err(ApiError::not_found(format!("task {tid}")));
    };
    if !matches!(action, "steer" | "pause" | "resume" | "cancel") {
        return Err(ApiError::bad(format!("unknown task action `{action}`")));
    }
    if let Some(r) = relay_if_held(
        &state,
        &p,
        task.session_id,
        cid,
        &format!("Task:{action}"),
        json!({"task_id": tid.to_string(), "text": body["text"], "reason": body["reason"]}),
    )
    .await?
    {
        return Ok(r);
    }
    let who = format!("{}:{}", p.kind, p.label);
    let (event_type, payload, note): (&str, TaskEvent, &str) = match action {
        "steer" => {
            let text = body["text"].as_str().unwrap_or_default().trim().to_owned();
            if text.is_empty() || text.len() > 16 * 1024 {
                return Err(ApiError::bad("text required"));
            }
            (
                "TaskInputQueued",
                TaskEvent::TaskInputQueued {
                    input_id: cid.to_string(),
                    mode: InputMode::Steer,
                    text,
                },
                "queued",
            )
        }
        "pause" => (
            "TaskPauseRequested",
            TaskEvent::TaskPauseRequested {
                requested_by: who.clone(),
            },
            "requested",
        ),
        "resume" => (
            "TaskResumeRequested",
            TaskEvent::TaskResumeRequested {
                requested_by: who.clone(),
            },
            "requested",
        ),
        "cancel" => {
            let reason = body["reason"]
                .as_str()
                .unwrap_or("cancelled by the person")
                .to_owned();
            // No execution owner holds the session (a held one is relayed
            // above): the cancel is durable here for a task that has not run;
            // a task an owner left running gets the request on its log.
            if matches!(
                task.state,
                TaskState::Created | TaskState::Queued | TaskState::Waiting(_)
            ) {
                ("TaskCancelled", TaskEvent::TaskCancelled, "cancelled")
            } else if matches!(
                task.state,
                TaskState::Completed | TaskState::Failed | TaskState::Cancelled
            ) {
                return Err(ApiError::new(
                    StatusCode::CONFLICT,
                    "TASK_TERMINAL",
                    format!("task {tid} is {:?}", task.state),
                ));
            } else {
                (
                    "TaskCancelRequested",
                    TaskEvent::TaskCancelRequested {
                        requested_by: who.clone(),
                        reason,
                    },
                    "requested",
                )
            }
        }
        other => return Err(ApiError::bad(format!("unknown task action `{other}`"))),
    };
    let ev = new_event(event_type, &payload, api_actor(&p))?;
    let result = json!({"task_id": tid.to_string(), "action": action, "outcome": note, "event_type": event_type});
    let appended = state
        .store
        .append(
            AppendRequest {
                tenant_id: p.tenant_id,
                session_id: task.session_id,
                task_id: Some(tid),
                run_id: None,
                turn_id: None,
                step_id: None,
                aggregate_type: AggregateType::Task,
                aggregate_id: *tid.as_bytes(),
                expected_sequence: None,
                events: vec![ev],
            },
            Some((cid, &format!("Task:{action}"), result.clone())),
        )
        .await?;
    let mut out = result;
    out["session_offset"] = json!(appended.session_offset);
    Ok((StatusCode::OK, Json(out)).into_response())
}

/// `POST /v1/approvals/{approval_id}:approve|:deny {command_id, intent_hash, reason}`.
async fn approval_action(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(seg): Path<String>,
    Json(body): Json<Value>,
) -> ApiResult<Response> {
    let p = caller(&ext);
    let (id, action) = seg
        .split_once(':')
        .ok_or_else(|| ApiError::bad("expected /v1/approvals/{approval_id}:approve|:deny"))?;
    let aid = parse_id(id, |s| ApprovalId::parse(s).ok(), "approval_id")?;
    let cid = command_id(&body)?;
    if let Some(r) = replay(&state, p.tenant_id, cid).await? {
        return Ok(r);
    }
    let approved = match action {
        "approve" => true,
        "deny" => false,
        other => return Err(ApiError::bad(format!("unknown approval action `{other}`"))),
    };
    let Some((approval, session_id)) = state.store.approval(p.tenant_id, aid).await? else {
        state
            .store
            .record_denial(
                Some(p.tenant_id),
                Some(p.principal_id),
                &format!("approval:{aid}"),
                "not in tenant",
            )
            .await?;
        return Err(ApiError::not_found(format!("approval {aid}")));
    };
    if let Some(r) = relay_if_held(
        &state,
        &p,
        session_id,
        cid,
        &format!("Approval:{action}"),
        json!({"approval_id": aid.to_string(), "intent_hash": body["intent_hash"], "reason": body["reason"]}),
    )
    .await?
    {
        return Ok(r);
    }
    let intent = body["intent_hash"].as_str().unwrap_or_default();
    if intent != approval.intent_hash {
        let result = json!({"code": "INTENT_MISMATCH", "message": "the intent hash is not the one the approval was opened for", "status": 409});
        state
            .store
            .record_rejection(
                p.tenant_id,
                cid,
                &format!("Approval:{action}"),
                "INTENT_MISMATCH",
                result,
            )
            .await?;
        return Err(ApiError::new(
            StatusCode::CONFLICT,
            "INTENT_MISMATCH",
            "the intent hash is not the one the approval was opened for",
        ));
    }
    if !matches!(
        approval.state,
        modbit_domain::approval::ApprovalState::Requested
    ) {
        return Err(ApiError::new(
            StatusCode::CONFLICT,
            "APPROVAL_NOT_OPEN",
            format!("approval {aid} is {:?}", approval.state),
        ));
    }
    let ev = new_event(
        "ApprovalResolved",
        &ApprovalEvent::ApprovalResolved {
            approved,
            resolver: format!("{}:{}", p.kind, p.label),
            reason: body["reason"].as_str().unwrap_or_default().to_owned(),
        },
        api_actor(&p),
    )?;
    let result = json!({"approval_id": aid.to_string(), "status": if approved { "APPROVED" } else { "DENIED" }, "intent_hash": approval.intent_hash});
    state
        .store
        .append(
            AppendRequest {
                tenant_id: p.tenant_id,
                session_id,
                task_id: Some(approval.task_id),
                run_id: None,
                turn_id: None,
                step_id: None,
                aggregate_type: AggregateType::Approval,
                aggregate_id: *aid.as_bytes(),
                expected_sequence: Some(approval.generation),
                events: vec![ev],
            },
            Some((cid, &format!("Approval:{action}"), result.clone())),
        )
        .await?;
    Ok((StatusCode::OK, Json(result)).into_response())
}

#[derive(serde::Deserialize)]
struct EventsQuery {
    session_id: String,
    #[serde(default)]
    after: u64,
    #[serde(default)]
    limit: Option<u32>,
}

/// `GET /v1/events?session_id&after&limit`: cursor replay.
async fn events(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Query(q): Query<EventsQuery>,
) -> ApiResult<Json<Value>> {
    let p = caller(&ext);
    let sid = parse_id(&q.session_id, |s| SessionId::parse(s).ok(), "session_id")?;
    if state.store.session(p.tenant_id, sid).await?.is_none() {
        state
            .store
            .record_denial(
                Some(p.tenant_id),
                Some(p.principal_id),
                &format!("session:{sid}"),
                "not in tenant",
            )
            .await?;
        return Err(ApiError::not_found(format!("session {sid}")));
    }
    let events = state
        .store
        .events_after(p.tenant_id, sid, q.after, q.limit.unwrap_or(200))
        .await?;
    let next = events.last().map_or(q.after, |e| e.session_offset);
    Ok(Json(json!({"events": events, "next_after": next})))
}

#[derive(serde::Deserialize)]
struct RangeQuery {
    #[serde(default)]
    start: u64,
    #[serde(default)]
    len: Option<u64>,
}

/// `GET /v1/outputs/{hash}?start&len` (or a `Range: bytes=` header): a ranged read.
async fn output(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(hash): Path<String>,
    Query(q): Query<RangeQuery>,
    headers: HeaderMap,
) -> ApiResult<Response> {
    let p = caller(&ext);
    if hash.len() != 64 || !hash.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(ApiError::bad("hash must be 64 hex characters"));
    }
    let (mut start, mut len) = (q.start, q.len.unwrap_or(1024 * 1024).min(8 * 1024 * 1024));
    if let Some(r) = headers
        .get(header::RANGE)
        .and_then(|v| v.to_str().ok())
        .and_then(|v| v.strip_prefix("bytes="))
    {
        let (a, b) = r.split_once('-').unwrap_or((r, ""));
        start = a.parse().unwrap_or(0);
        if let Ok(end) = b.parse::<u64>() {
            len = end.saturating_sub(start).saturating_add(1);
        }
    }
    let got = state
        .store
        .get_object_range(p.tenant_id, &hash, start, len)
        .await;
    let (bytes, meta) = match got {
        Ok(x) => x,
        Err(CloudError::NotFound(_)) => {
            state
                .store
                .record_denial(
                    Some(p.tenant_id),
                    Some(p.principal_id),
                    &format!("object:{hash}"),
                    "not in tenant",
                )
                .await?;
            return Err(ApiError::not_found(format!("output {hash}")));
        }
        Err(e) => return Err(e.into()),
    };
    let end = start.min(meta.byte_length) + bytes.len() as u64;
    let mut res = (StatusCode::PARTIAL_CONTENT, Bytes::from(bytes)).into_response();
    let h = res.headers_mut();
    h.insert(
        header::CONTENT_TYPE,
        HeaderValue::from_str(&meta.mime)
            .unwrap_or(HeaderValue::from_static("application/octet-stream")),
    );
    h.insert(
        header::CONTENT_RANGE,
        HeaderValue::from_str(&format!(
            "bytes {}-{}/{}",
            start.min(meta.byte_length),
            end.saturating_sub(1),
            meta.byte_length
        ))
        .unwrap_or(HeaderValue::from_static("")),
    );
    h.insert(
        "x-modbit-byte-length",
        HeaderValue::from_str(&meta.byte_length.to_string())
            .unwrap_or(HeaderValue::from_static("0")),
    );
    let _ = request_id(&headers);
    Ok(res)
}

/// `GET /v1/artifacts/{hash}`: metadata and a short-lived access grant.
/// `PUT /v1/objects` (M8.7): a content-addressed object into the tenant's
/// store; the body is the bytes, the answer its hash. A handoff bundle's
/// parts arrive this way before the handoff names them.
async fn put_object(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    headers: HeaderMap,
    body: Bytes,
) -> ApiResult<(StatusCode, Json<Value>)> {
    let p = caller(&ext);
    if body.is_empty() {
        return Err(ApiError::bad("an object has bytes"));
    }
    let mime = headers
        .get(header::CONTENT_TYPE)
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream")
        .to_owned();
    let hash = state.store.put_object(p.tenant_id, &body, &mime).await?;
    Ok((
        StatusCode::CREATED,
        Json(json!({"hash": hash, "bytes": body.len()})),
    ))
}

/// What `cloud_isolated` serves a continuation (docs/21 "Execution
/// profiles" as built): the capability parity a handoff is checked against.
pub const CLOUD_CAPABILITIES: &[&str] = &[
    "fs.read",
    "fs.write",
    "git.read",
    "shell.exec",
    "network.egress",
    "secret.use",
    // M8.8: the browser inside the sandbox.
    "browser.control",
];

/// A worker that has not been seen for this long serves nothing.
const WORKER_LIVENESS_MS: i64 = 60_000;

/// What the cloud serves right now (IMP-EV-0072): the union of the
/// capabilities of the workers seen lately; the build's own set when no
/// worker has registered (a single-process deployment, the tests without
/// a worker).
async fn served_capabilities(state: &AppState) -> ApiResult<Vec<String>> {
    let live = state.store.live_workers(WORKER_LIVENESS_MS).await?;
    if live.is_empty() {
        return Ok(CLOUD_CAPABILITIES.iter().map(|s| (*s).to_owned()).collect());
    }
    let mut out: Vec<String> = Vec::new();
    for (_, caps) in live {
        for c in caps {
            if !out.contains(&c) {
                out.push(c);
            }
        }
    }
    out.sort();
    Ok(out)
}

/// Manifest keys that would carry authority or a credential into the
/// cloud: a capsule names requirements and handles, never grants or values.
const CAPSULE_AUTHORITY_KEYS: &[&str] = &[
    "lease",
    "leases",
    "capability_lease",
    "token",
    "tokens",
    "api_key",
    "api_keys",
    "secret",
    "secrets",
    "password",
    "credential",
    "credentials",
    "private_key",
    "boot_secret",
];

/// Shapes a secret value takes (a provider key, a forge token, a worker
/// token, a bearer, an AWS key id, a PEM private key).
fn secret_shaped(text: &str) -> Option<&'static str> {
    static SHAPES: std::sync::OnceLock<Vec<(regex::Regex, &'static str)>> =
        std::sync::OnceLock::new();
    let shapes = SHAPES.get_or_init(|| {
        [
            (r"\bsk-[A-Za-z0-9_-]{16,}", "a provider API key"),
            (r"\b(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{20,}", "a forge token"),
            (r"\bgithub_pat_[A-Za-z0-9_]{20,}", "a forge token"),
            (r"\bmbw_[0-9a-f]{8,}\.[0-9a-f]{16,}", "a worker token"),
            (r"\bBearer\s+[A-Za-z0-9._~+/=-]{20,}", "a bearer credential"),
            (r"\bAKIA[0-9A-Z]{16}\b", "an AWS access key id"),
            (r"-----BEGIN [A-Z ]*PRIVATE KEY-----", "a private key"),
        ]
        .into_iter()
        .map(|(re, what)| (regex::Regex::new(re).expect("a valid shape"), what))
        .collect()
    });
    shapes
        .iter()
        .find(|(re, _)| re.is_match(text))
        .map(|(_, what)| *what)
}

fn manifest_authority_key(v: &Value, path: &str) -> Option<String> {
    match v {
        Value::Object(m) => {
            for (k, child) in m {
                let here = if path.is_empty() {
                    k.clone()
                } else {
                    format!("{path}.{k}")
                };
                if CAPSULE_AUTHORITY_KEYS.contains(&k.as_str()) {
                    return Some(here);
                }
                if let Some(found) = manifest_authority_key(child, &here) {
                    return Some(found);
                }
            }
            None
        }
        Value::Array(a) => a
            .iter()
            .enumerate()
            .find_map(|(i, c)| manifest_authority_key(c, &format!("{path}[{i}]"))),
        _ => None,
    }
}

/// What a capsule must not carry (IMP-EV-0176): `(code, why)` when it does.
fn capsule_smuggles(manifest: &Value, log: Option<&str>) -> Option<(&'static str, String)> {
    if let Some(key) = manifest_authority_key(manifest, "") {
        return Some((
            "CAPSULE_SMUGGLES_AUTHORITY",
            format!(
                "the manifest carries `{key}`; a handoff names requirements and handles, never a grant or a credential"
            ),
        ));
    }
    if !manifest.is_null()
        && let Some(what) = secret_shaped(&manifest.to_string())
    {
        return Some((
            "CAPSULE_SMUGGLES_SECRET",
            format!("the manifest carries {what}; no secret value crosses in a handoff"),
        ));
    }
    if let Some(text) = log
        && let Some(what) = secret_shaped(text)
    {
        return Some((
            "CAPSULE_SMUGGLES_SECRET",
            format!("the bundled log carries {what}; no secret value crosses in a handoff"),
        ));
    }
    None
}

/// `POST /v1/handoffs {command_id, manifest, parts: {events.jsonl: hash, repo.bundle?: hash, manifest.json: hash}}`
/// (M8.7, docs/21 "Handoff local → cloud"; docs/30): admit a local task's
/// continuation. Cloud admission verifies capability parity before the
/// execution owner switches: a continuation needing what `cloud_isolated`
/// does not serve (a browser session, say) is refused `CAPABILITY_PARITY`.
/// Then the session's log is imported verbatim, `TaskHandoffAdmitted` is
/// recorded on the task, and the session is marked ready for a worker.
async fn handoff(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Json(body): Json<Value>,
) -> ApiResult<Response> {
    let p = caller(&ext);
    let cid = command_id(&body)?;
    if let Some(r) = replay(&state, p.tenant_id, cid).await? {
        return Ok(r);
    }
    let manifest = &body["manifest"];
    if manifest["kind"] != "modbit-handoff" {
        return Err(ApiError::bad("manifest.kind must be modbit-handoff"));
    }
    let sid = parse_id(
        manifest["session_id"].as_str().unwrap_or_default(),
        |s| SessionId::parse(s).ok(),
        "manifest.session_id",
    )?;
    let tid = parse_id(
        manifest["task_id"].as_str().unwrap_or_default(),
        |s| TaskId::parse(s).ok(),
        "manifest.task_id",
    )?;
    let capabilities: Vec<String> = manifest["capabilities"]
        .as_array()
        .map(|a| {
            a.iter()
                .filter_map(|c| c.as_str().map(str::to_owned))
                .collect()
        })
        .unwrap_or_default();
    let served = served_capabilities(&state).await?;
    let missing: Vec<&String> = capabilities
        .iter()
        .filter(|c| !served.iter().any(|s| s == *c))
        .collect();
    if !missing.is_empty() {
        let result = json!({"code": "CAPABILITY_PARITY", "missing": missing, "served": served});
        state
            .store
            .record_rejection(
                p.tenant_id,
                cid,
                "Handoff",
                "CAPABILITY_PARITY",
                result.clone(),
            )
            .await?;
        return Err(ApiError::new(
            StatusCode::CONFLICT,
            "CAPABILITY_PARITY",
            format!(
                "the continuation needs {:?}, which cloud_isolated does not serve",
                missing
            ),
        ));
    }
    // IMP-EV-0176 (the capsule): a handoff carries context, decisions,
    // evidence and requirements — never authority or a secret value. A
    // manifest with a grant or credential field, or a secret-shaped value
    // anywhere in the manifest or the log, is refused before anything is
    // admitted; the refusal is on the ledger.
    if let Some((code, why)) = capsule_smuggles(manifest, None) {
        state
            .store
            .record_rejection(
                p.tenant_id,
                cid,
                "Handoff",
                code,
                json!({"code": code, "why": why}),
            )
            .await?;
        return Err(ApiError::new(StatusCode::CONFLICT, code, why));
    }
    let Some(events_hash) = body["parts"]["events.jsonl"].as_str() else {
        return Err(ApiError::bad(
            "parts[\"events.jsonl\"] (an uploaded object's hash) is required",
        ));
    };
    let Some(manifest_hash) = body["parts"]["manifest.json"].as_str() else {
        return Err(ApiError::bad(
            "parts[\"manifest.json\"] (an uploaded object's hash) is required",
        ));
    };
    let raw = match state.store.get_object(p.tenant_id, events_hash).await {
        Ok(b) => b,
        Err(CloudError::NotFound(_)) => {
            return Err(ApiError::new(
                StatusCode::UNPROCESSABLE_ENTITY,
                "PART_MISSING",
                format!("events.jsonl {events_hash} was not uploaded to this tenant"),
            ));
        }
        Err(e) => return Err(e.into()),
    };
    if let Some((code, why)) = capsule_smuggles(&Value::Null, Some(&String::from_utf8_lossy(&raw)))
    {
        state
            .store
            .record_rejection(
                p.tenant_id,
                cid,
                "Handoff",
                code,
                json!({"code": code, "why": why}),
            )
            .await?;
        return Err(ApiError::new(StatusCode::CONFLICT, code, why));
    }
    let mut events = Vec::new();
    for line in String::from_utf8_lossy(&raw).lines() {
        if line.trim().is_empty() {
            continue;
        }
        let v: Value =
            serde_json::from_str(line).map_err(|e| ApiError::bad(format!("events.jsonl: {e}")))?;
        let env: modbit_domain::event::EventEnvelope =
            serde_json::from_value(v["envelope"].clone())
                .map_err(|e| ApiError::bad(format!("events.jsonl envelope: {e}")))?;
        events.push((env, v["payload"].clone()));
    }
    if !events
        .iter()
        .any(|(e, _)| e.aggregate_id == *tid.as_bytes())
    {
        return Err(ApiError::bad(
            "the log carries no event of manifest.task_id",
        ));
    }
    let from_tenant = events
        .first()
        .map(|(e, _)| e.tenant_id.to_string())
        .unwrap_or_default();
    // The admitted manifest: the local manifest plus where its parts are
    // in this tenant's store — what a worker materializes from.
    let mut admitted = manifest.clone();
    admitted["parts"] = body["parts"].clone();
    admitted["admitted_by"] = json!(p.principal_id.to_string());
    admitted["local_manifest_hash"] = json!(manifest_hash);
    let admitted_bytes = serde_json::to_vec(&admitted).map_err(|e| ApiError::bad(e.to_string()))?;
    let bundle_hash = state
        .store
        .put_object(p.tenant_id, &admitted_bytes, "application/json")
        .await?;
    let imported = state
        .store
        .import_handoff(p.tenant_id, sid, events)
        .await
        .map_err(|e| match e {
            CloudError::Integrity(m) => {
                ApiError::new(StatusCode::CONFLICT, "HANDOFF_LOG_INTEGRITY", m)
            }
            CloudError::SequenceConflict { .. } => {
                ApiError::new(StatusCode::CONFLICT, "HANDOFF_LOG_FORK", e.to_string())
            }
            other => other.into(),
        })?;
    let ev = new_event(
        "TaskHandoffAdmitted",
        &TaskEvent::TaskHandoffAdmitted {
            bundle_hash: bundle_hash.clone(),
            from_tenant: from_tenant.clone(),
            capabilities: capabilities.clone(),
        },
        api_actor(&p),
    )?;
    let result = json!({
        "session_id": sid.to_string(), "task_id": tid.to_string(), "bundle_hash": bundle_hash, "local_manifest_hash": manifest_hash,
        "imported_through": imported.session_offset, "capabilities": capabilities,
    });
    state
        .store
        .append(
            AppendRequest {
                tenant_id: p.tenant_id,
                session_id: sid,
                task_id: Some(tid),
                run_id: None,
                turn_id: None,
                step_id: None,
                aggregate_type: AggregateType::Task,
                aggregate_id: *tid.as_bytes(),
                expected_sequence: None,
                events: vec![ev],
            },
            Some((cid, "Handoff", result.clone())),
        )
        .await?;
    // The continuation's requirements: only a worker serving them claims it.
    state
        .store
        .require_for_session(p.tenant_id, sid, &capabilities)
        .await?;
    state.store.mark_ready(p.tenant_id, sid).await?;
    Ok((StatusCode::CREATED, Json(result)).into_response())
}

async fn artifact(
    State(state): State<Arc<AppState>>,
    ext: axum::Extension<Caller>,
    Path(hash): Path<String>,
) -> ApiResult<Json<Value>> {
    let p = caller(&ext);
    let Some(meta) = state.store.object_meta(p.tenant_id, &hash).await? else {
        state
            .store
            .record_denial(
                Some(p.tenant_id),
                Some(p.principal_id),
                &format!("object:{hash}"),
                "not in tenant",
            )
            .await?;
        return Err(ApiError::not_found(format!("artifact {hash}")));
    };
    let url = state
        .store
        .signed_get_url(p.tenant_id, &hash, std::time::Duration::from_secs(300))
        .await?;
    Ok(Json(
        json!({"hash": meta.hash, "byte_length": meta.byte_length, "mime": meta.mime, "url": url, "url_expires_in_ms": 300_000}),
    ))
}
